Feat: Trip title / description character limit
binhonglee/GlobeTrotte pull request #484
Opened 2021-06-05 22:05 UTC by samueljklee

[Trip title / description character limit](https://github.com/binhonglee/GlobeTrotte/wiki/Roadmap)

As discussed with @binhonglee , Title limit 50, Description limit 500

2021-06-06 01:51 UTC, binhonglee requested changes
Seems like this is only to limit rendering of characters when user is editing the trip? Can we also add these limitation to `save()` in `CEditTrip()` so it shows an alert when users trying to save trip title / description over the limit?

2021-06-06 01:51 UTC, binhonglee commented on src/cockpit/tests/components/CEditItem.test.ts
> +const mockedTrip = new mockTripObj();
Remove this? (and the import above) since its not used.

2021-06-06 01:54 UTC, binhonglee commented
Code pointer: https://github.com/binhonglee/GlobeTrotte/blob/main/src/cockpit/components/CEditTrip.vue#L106-L157

You can see how it shows an alert [here](https://github.com/binhonglee/GlobeTrotte/blob/main/src/cockpit/components/CEditTrip.vue#L133-L143) when the place input does not fit the requirement.

2021-06-06 05:53 UTC, binhonglee reviewed
Do you think you can add some simple `CEditTrip` test as well? Current `CEditTrip` test is broken and can be deleted tbh.

LGTM otherwise

Let me know again when you're ready to merge and I'll approve it (mergify will auto-merge once I approve lol).

2021-06-06 05:53 UTC, binhonglee commented on src/cockpit/components/CEditTrip.vue
> +      if (description.length > DESCRIPTION_CHAR_MAX_COUNT) {
Do we want to add `!description` check as well?

2021-06-06 05:53 UTC, binhonglee commented on src/cockpit/components/CEditTrip.vue
> +      console.table([name, description]);
remove this?

2021-06-06 05:53 UTC, binhonglee commented on src/cockpit/components/CEditItem.vue
> +const DESCRIPTION_ROW_COUNT = 3;
Can we move this to `CEditTrip` as well? `CEditItem` is supposed to be pretty general and is currently used in many places including registration and login. We might not want to have the same restrictions for them.

2021-06-06 05:53 UTC, binhonglee commented on src/cockpit/components/CEditItem.vue
> +    },
We can turn this into a more generic prop that can be used by other UI components. (say something like minimum password length) and have it as empty by default.

2021-06-06 07:39 UTC, samueljklee commented on src/cockpit/components/CEditItem.vue
> +    },
What about `itemCharMaxCount`? We let parent component to specifically pass the max count? What's a default would be good? 50 char?

2021-06-06 07:42 UTC, samueljklee commented on src/cockpit/components/CEditItem.vue
> +const DESCRIPTION_ROW_COUNT = 3;
We'll have this as props as well? And we'll have default as 1 row. How about that?

2021-06-06 10:12 UTC, binhonglee commented on src/cockpit/components/CEditItem.vue
> +    },
Yea that sounds good.

2021-06-06 10:14 UTC, binhonglee commented on src/cockpit/components/CEditItem.vue
> +const DESCRIPTION_ROW_COUNT = 3;
Yea I think that was the behavior before. Its 1 by default unless `$this.props.type` is specified as `textarea`.

2021-06-07 00:30 UTC, samueljklee commented on src/cockpit/components/CEditTrip.vue
> +      if (description.length > DESCRIPTION_CHAR_MAX_COUNT) {
added

2021-06-07 00:31 UTC, samueljklee commented on src/cockpit/components/CEditItem.vue
> +const DESCRIPTION_ROW_COUNT = 3;
refactored

2021-06-07 00:31 UTC, samueljklee commented on src/cockpit/components/CEditItem.vue
> +    },
refactored

2021-06-07 00:44 UTC, binhonglee approved these changes

2021-06-07 00:58 UTC, binhonglee commented on src/cockpit/tests/components/CEditTrip.test.ts
> +        trip,
`isNew` is a required param that caused the typecheck error.

```suggestion
        trip: trip,
        isNew: false,
```

2021-06-07 01:06 UTC, binhonglee commented
Oh shoot. I didn't update the mergify rule since I split gh-action into multi parts. Merging this manually instead.

2021-06-07 01:08 UTC, merged